//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diet_and_Exercise_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUT_DATA
    {
        public string NDB_No { get; set; }
        public string Nutr_No { get; set; }
        public Nullable<double> Nutr_Val { get; set; }
        public Nullable<int> Num_Data_Pts { get; set; }
        public Nullable<double> Std_Error { get; set; }
        public string Src_Cd { get; set; }
        public string Deriv_Cd { get; set; }
        public string Ref_NDB_No { get; set; }
        public string Add_Nutr_Mark { get; set; }
        public Nullable<short> Num_Studies { get; set; }
        public Nullable<double> Min { get; set; }
        public Nullable<double> Max { get; set; }
        public Nullable<double> DF { get; set; }
        public Nullable<double> Low_EB { get; set; }
        public Nullable<double> Up_EB { get; set; }
        public string Stat_Cmt { get; set; }
        public string AddMod_Date { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual NUTR_DEF NUTR_DEF { get; set; }
    }
}
