//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diet_and_Exercise_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEIGHT
    {
        public string NDB_No { get; set; }
        public string Seq { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Msre_Desc { get; set; }
        public Nullable<double> Gm_Wgt { get; set; }
        public Nullable<short> Num_Data_Pts { get; set; }
        public Nullable<double> Std_Dev { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual FOOD_DES FOOD_DES { get; set; }
    }
}
